#Get all persons 
GET http://localhost:3001/api/persons
###
# Get a single person
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/6

###
# Delete a single person 
DELETE http://localhost:3001/api/persons/2

###
# Add a single person 
POST http://localhost:3001/api/persons 
Content-Type: application/json 

{
    "name": "Yuri",
    "number": "234-1088"
}
